/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfazGráfica;

import ControladorDAO.GestionBBDD;
import ControladorDAO.InterfazDAO;
import Excepciones.ExcepcionMia;
import Modelo.Juego;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardolucasmunozdelucas
 */
public class Eliminar extends javax.swing.JDialog {

    StringBuilder userInput = new StringBuilder();
    private InterfazDAO daoEst = new GestionBBDD();
    ;
    private ArrayList<Juego> juegos = new ArrayList<>();
    Juego j;
    Juego z;
    String juegoSelecionado;

    int id;
    private String nombreFinal;
    String disenador;
    int año;
    int numJugMax;
    int numJugMin;
    int duracion;
    String tematica;
    int dificultad;
    int estrategia;
    int suerte;
    int interaccion;
    String dueno;
    boolean expansion;
    String expansionDe;
    String descripcion;

    /**
     * Creates new form Eliminar
     */
    public Eliminar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        jTextField1Buscador.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char keyChar = e.getKeyChar();
                if (Character.isLetter(keyChar) || Character.isWhitespace(keyChar)) {
                    userInput.append(keyChar);
                } else if (keyChar == KeyEvent.VK_BACK_SPACE && userInput.length() > 0) {
                    userInput.deleteCharAt(userInput.length() - 1);
                }

                
                actualizarComboBox();

            }
        });

    }

    private void actualizarComboBox() {
        
        if (userInput.length() == 0) {
        jComboBox1Juegosencontrados.removeAllItems();
        return;
    }
        try {
            juegos = daoEst.buscarporNombreConLetras(userInput.toString() + "%");
        } catch (ExcepcionMia ex) {
            Logger.getLogger(Modificar2.class.getName()).log(Level.SEVERE, null, ex);
        }

        jComboBox1Juegosencontrados.removeAllItems();
        if (!juegos.isEmpty()) {
            for (Juego j : juegos) {
                jComboBox1Juegosencontrados.addItem(j.getNombre());
               jComboBox1Juegosencontrados.setPopupVisible(true);
            }
        } else {
            jComboBox1Juegosencontrados.addItem("---");
        }

        System.out.println("Texto actual: " + userInput.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1Buscador = new javax.swing.JTextField();
        jComboBox1Juegosencontrados = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Escribe el nombre:");

        jLabel2.setText("Seleciona el juego que quieras borrar:");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1Buscador, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1Juegosencontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1Juegosencontrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jComboBox1Juegosencontrados.getSelectedItem() != null) {
            juegoSelecionado = jComboBox1Juegosencontrados.getSelectedItem().toString();
            // Buscar el juego seleccionado en la lista de juegos
            for (Juego juego : juegos) {
                if (juego.getNombre().equals(juegoSelecionado)) {
                    j = juego;
                    break;
                }
            }
            if (j != null) {
                boolean ok = true;
                do {
                    try {
                        int juegoEliminado = daoEst.elimniar(j);
                        if (juegoEliminado == 1) {
                            JOptionPane.showMessageDialog(this, "Juego eliminado", "Juego eliminado", JOptionPane.INFORMATION_MESSAGE);
                            ok = false;
                        } else {
                            JOptionPane.showMessageDialog(this, "Juego no borrado, vuelve a intentarlo ", "Error ", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                    } catch (ExcepcionMia ex) {
                        Logger.getLogger(Eliminar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }while(ok == true);
                dispose();
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Eliminar dialog = new Eliminar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1Juegosencontrados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1Buscador;
    // End of variables declaration//GEN-END:variables
}
