/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfazGráfica;

import ControladorDAO.GestionBBDD;
import ControladorDAO.InterfazDAO;
import Excepciones.ExcepcionMia;
import Modelo.Juego;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author eduardolucasmunozdelucas
 */
public class IngresarJuego extends javax.swing.JDialog {

    private InterfazDAO daoEst;
    private String nombre;
    String disenador;
    int año;
    int numJugMax;
    int numJugMin;
    int duracion;
    String tematica;
    int dificultad;
    int estrategia;
    int suerte;
    int interaccion;
    String dueno;
    boolean expansion;
    String expansionDe;
    String descripcion;

    /**
     * Creates new form IngresarJuego
     */
    public IngresarJuego(java.awt.Frame parent, boolean modal)  {
        super(parent, modal);
        initComponents();

        daoEst = new GestionBBDD();
        Calendar cal = Calendar.getInstance();
        String numMaxJugSelecionado;

        for (int i = cal.get(Calendar.YEAR)+1; i >= 1980; i--) {
            if(i==cal.get(Calendar.YEAR)+1){
                jComboBox1Año.addItem(" ");
            }else{
                 jComboBox1Año.addItem(String.valueOf(i));
            }
           
        }

        for (int i = 1; i < 21; i++) {
            jComboBox1NJugMax.addItem(String.valueOf(i));
        }
        // Desactivar el segundo JComboBox al inicio
        jComboBox1NumJugMin.setEnabled(false);

        // Agregar un ActionListener al primer JComboBox
        jComboBox1NJugMax.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jComboBox1NJugMax.getSelectedItem() != null) {
                    // Limpiar el segundo JComboBox
                    jComboBox1NumJugMin.removeAllItems();

                    // Obtener el valor seleccionado en el primer JComboBox
                    numJugMax = Integer.parseInt(jComboBox1NJugMax.getSelectedItem().toString());

                    // Llenar el segundo JComboBox con valores apropiados
                    for (int i = 1; i <= numJugMax; i++) {
                        jComboBox1NumJugMin.addItem(String.valueOf(i));
                    }

                    // Activar el segundo JComboBox
                    jComboBox1NumJugMin.setEnabled(true);
                }
            }
        });

        for (int i = 5; i < 241; i += 5) {
            jComboBox1Duracion.addItem(String.valueOf(i));
        }

//        jTextField1ExoansionDe.setEnabled(false);
        jComboBox1listadojuegos.setEnabled(false);
        
        jComboBox1Expansion.addItem("");
        jComboBox1Expansion.addItem("si");
        jComboBox1Expansion.addItem("no");
        
        try {
            for (Juego s : daoEst.leerTodos()){
                if(s.isExpansion() == false){
                jComboBox1listadojuegos.addItem(String.valueOf(s.getNombre()));
                }
            }
        } catch (ExcepcionMia ex) {
            Logger.getLogger(IngresarJuego.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox1Duracion.setSelectedIndex(4);
        
        
        
        jComboBox1Expansion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jComboBox1Expansion.getSelectedItem() != null
                        && jComboBox1Expansion.getSelectedItem().toString().equalsIgnoreCase("si")) {
                    jComboBox1listadojuegos.setEnabled(true);
                } else {
                    jComboBox1listadojuegos.setEnabled(false);
                }
            }
        });

        jComboBox1dueño.addItem("");
        jComboBox1dueño.addItem("Edu");
        jComboBox1dueño.addItem("Diana");

    }

     public int getSelectedRadioButtonValue(JRadioButton... buttons) {
        for (int i = 0; i < buttons.length; i++) {
            if (buttons[i].isSelected()) {
                return i + 1;
            }
        }
        return 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupodificultad = new javax.swing.ButtonGroup();
        buttonGroup1Experiencia = new javax.swing.ButtonGroup();
        GrupoSuerte = new javax.swing.ButtonGroup();
        GrupoInteraccion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1Nombre = new javax.swing.JTextField();
        jButton1Ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1disenador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1Año = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1NJugMax = new javax.swing.JComboBox<>();
        jComboBox1NumJugMin = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1Duracion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField2temática = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Boton1dif = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Boton2dif = new javax.swing.JRadioButton();
        Boton3dif = new javax.swing.JRadioButton();
        Boton4dif = new javax.swing.JRadioButton();
        Boton5dif = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1Expansion = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1dueño = new javax.swing.JComboBox<>();
        jComboBox1listadojuegos = new javax.swing.JComboBox<>();
        Botonest1 = new javax.swing.JRadioButton();
        Botonest2 = new javax.swing.JRadioButton();
        Botonest3 = new javax.swing.JRadioButton();
        Botonest4 = new javax.swing.JRadioButton();
        Botonest5 = new javax.swing.JRadioButton();
        Boton1suerte = new javax.swing.JRadioButton();
        Boton2suerte = new javax.swing.JRadioButton();
        Boton3suerte = new javax.swing.JRadioButton();
        Boton4suerte = new javax.swing.JRadioButton();
        Boton5suerte = new javax.swing.JRadioButton();
        Boton1inter = new javax.swing.JRadioButton();
        Boton3inter = new javax.swing.JRadioButton();
        Boton4inter = new javax.swing.JRadioButton();
        Boton5inter = new javax.swing.JRadioButton();
        Boton2inter = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Juego nuevo o Expansión");

        jLabel1.setText("Nombre del juego:");

        jButton1Ok.setText("Ok");
        jButton1Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OkActionPerformed(evt);
            }
        });

        jLabel2.setText("Diseñador: ");

        jLabel3.setText("Año de creación:");

        jLabel4.setText("Nº jugadores máximo: ");

        jLabel5.setText("Nº jugadores mínimo: ");

        jLabel6.setText("Duración de una partida:");

        jLabel7.setText("Temática:");

        jLabel8.setText("Elige el grado de los siguientes items siendo 5 mucho y 1 poco:");

        jLabel9.setText("Dificultad:");

        grupodificultad.add(Boton1dif);

        jLabel10.setText("Estrategía:");

        jLabel11.setText("Suerte:");

        jLabel12.setText("Interacción:");

        grupodificultad.add(Boton2dif);

        grupodificultad.add(Boton3dif);

        grupodificultad.add(Boton4dif);

        grupodificultad.add(Boton5dif);

        jLabel13.setText("1");

        jLabel14.setText("5");

        jLabel15.setText("¿Este juego es una expansión?");

        jLabel16.setText("Dueño del juego:");

        buttonGroup1Experiencia.add(Botonest1);

        buttonGroup1Experiencia.add(Botonest2);
        Botonest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botonest2ActionPerformed(evt);
            }
        });

        buttonGroup1Experiencia.add(Botonest3);

        buttonGroup1Experiencia.add(Botonest4);

        buttonGroup1Experiencia.add(Botonest5);

        GrupoSuerte.add(Boton1suerte);

        GrupoSuerte.add(Boton2suerte);

        GrupoSuerte.add(Boton3suerte);

        GrupoSuerte.add(Boton4suerte);

        GrupoSuerte.add(Boton5suerte);

        GrupoInteraccion.add(Boton1inter);

        GrupoInteraccion.add(Boton3inter);

        GrupoInteraccion.add(Boton4inter);

        GrupoInteraccion.add(Boton5inter);

        GrupoInteraccion.add(Boton2inter);

        jLabel17.setText("2");

        jLabel18.setText("3");

        jLabel19.setText("4");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1Ok))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1Expansion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1listadojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(51, 51, 51)
                            .addComponent(jComboBox1dueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2temática, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1NumJugMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1NJugMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBox1Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1Nombre)
                                .addComponent(jTextField1disenador, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Botonest1)
                                    .addGap(18, 18, 18)
                                    .addComponent(Botonest2)
                                    .addGap(18, 18, 18)
                                    .addComponent(Botonest3)
                                    .addGap(18, 18, 18)
                                    .addComponent(Botonest4)
                                    .addGap(18, 18, 18)
                                    .addComponent(Botonest5))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Boton1dif)
                                        .addComponent(jLabel13))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Boton2dif)
                                        .addComponent(jLabel17))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Boton3dif)
                                        .addComponent(jLabel18))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Boton4dif)
                                        .addComponent(jLabel19))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(Boton5dif)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Boton1suerte)
                                    .addGap(18, 18, 18)
                                    .addComponent(Boton2suerte)
                                    .addGap(18, 18, 18)
                                    .addComponent(Boton3suerte)
                                    .addGap(18, 18, 18)
                                    .addComponent(Boton4suerte)
                                    .addGap(18, 18, 18)
                                    .addComponent(Boton5suerte))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Boton1inter)
                                    .addGap(18, 18, 18)
                                    .addComponent(Boton2inter)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Boton3inter)
                                    .addGap(18, 18, 18)
                                    .addComponent(Boton4inter)
                                    .addGap(18, 18, 18)
                                    .addComponent(Boton5inter))))
                        .addComponent(jScrollPane1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1disenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1NJugMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1NumJugMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2temática, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel19))
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton1dif, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton2dif, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton3dif, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton4dif, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton5dif, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Botonest1)
                    .addComponent(jLabel10)
                    .addComponent(Botonest2)
                    .addComponent(Botonest3)
                    .addComponent(Botonest4)
                    .addComponent(Botonest5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton1suerte)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(Boton2suerte, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(Boton3suerte, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Boton4suerte, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(Boton5suerte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(Boton1inter))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Boton2inter)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Boton3inter)
                            .addComponent(Boton4inter))
                        .addComponent(Boton5inter)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox1Expansion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1listadojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox1dueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Ok)
                    .addComponent(jButton1))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1OkActionPerformed
        try {
            boolean ok = true;
            do {
//        daoEst = new GestionBBDD();
                nombre = jTextField1Nombre.getText();
                disenador = jTextField1disenador.getText();
                dueno = jComboBox1dueño.getSelectedItem().toString();
                tematica = jTextField2temática.getText();
                
//                if (jTextArea1.getSelectedText()!= null){
                    descripcion = jTextArea1.getText();
//                }else{
//                    descripcion = "--- sin descripción ---";
//                }

                dificultad = getSelectedRadioButtonValue(Boton1dif, Boton2dif, Boton3dif, Boton4dif, Boton5dif);
                estrategia = getSelectedRadioButtonValue(Botonest1, Botonest2, Botonest3, Botonest4, Botonest5);
                suerte = getSelectedRadioButtonValue(Boton1suerte, Boton2suerte, Boton3suerte, Boton4suerte, Boton5suerte);
                interaccion = getSelectedRadioButtonValue(Boton1inter, Boton2inter, Boton3inter, Boton4inter, Boton5inter);


                if (nombre.isEmpty() || disenador.isEmpty() || tematica.isEmpty() || dueno.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No se puede dejar campos en blanco", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                    return;
                    
                    //Este es el apartado que quiero saber como hacer
                    
                }else if(daoEst.leerJuego(new Juego(nombre)) != null){
                    JOptionPane.showMessageDialog(this, "Este nombre ya existe", "Nombre no válido", JOptionPane.WARNING_MESSAGE);
                    return;
                    
                    
                    
                            
                } else {
                     if (jComboBox1NJugMax.getSelectedItem() == null || jComboBox1Año.getSelectedItem() == null || jComboBox1Duracion.getSelectedItem() == null || jComboBox1NumJugMin.getSelectedItem() == null || jComboBox1Expansion.getSelectedItem() == null || dueno.isEmpty() ||jComboBox1Expansion.getSelectedItem() == "") {
                        JOptionPane.showMessageDialog(this, "No se puede dejar desplegables sin selecionar", "Despelgables vacíos", JOptionPane.WARNING_MESSAGE);
                        return;
                    } else {
                        año = Integer.parseInt(jComboBox1Año.getSelectedItem().toString());
                        numJugMin = Integer.parseInt(jComboBox1NumJugMin.getSelectedItem().toString());
                        numJugMax = Integer.parseInt(jComboBox1NJugMax.getSelectedItem().toString());
                        duracion = Integer.parseInt(jComboBox1Duracion.getSelectedItem().toString());

                        if (jComboBox1Expansion.getSelectedItem().toString() == "si") {
                            expansion = true;
                            
                            if(jComboBox1listadojuegos.getSelectedItem() == null){
                                JOptionPane.showMessageDialog(this, "No se puede dejar desplegables sin selecionar", "Despelgables vacíos", JOptionPane.WARNING_MESSAGE);
                                return;
                            }else{
                                expansionDe = jComboBox1listadojuegos.getSelectedItem().toString();
                                ok = false;
                            }

                        } else if (jComboBox1Expansion.getSelectedItem().toString() == "no") {
                            expansion = false;
                            ok = false;
                        }
                    }

                }

            } while (ok == true);

            Juego j;
            if (expansion == true) {
                
                j = new Juego(nombre, disenador, año, numJugMax, numJugMin, duracion, tematica, dificultad, estrategia, suerte, interaccion, dueno, expansion, expansionDe, descripcion);
            } else {
                j = new Juego(nombre, disenador, año, numJugMax, numJugMin, duracion, tematica, dificultad, estrategia, suerte, interaccion, dueno, expansion, descripcion);
            }

            
            int juegoIngresado = daoEst.insertar(j);
            
            if (juegoIngresado == 1) {
                    
                // Aquí tengo el problema con los metodos leer 2 y actualizar expansiones
                    Juego juegoBase = daoEst.leerExpansiones(new Juego(expansionDe));
                    if (juegoBase != null) {
                        juegoBase.getListaExpansiones().add(nombre);
                        daoEst.actualizarExpansiones(juegoBase);
                    }
                
                    JOptionPane.showMessageDialog(this, "Juego agregado", "Juego agregado", JOptionPane.INFORMATION_MESSAGE);
                    
                    
                    
                    System.out.println("El Juego " + j.getNombre()+ " ha sido agregado.");
                } else {
                    System.out.println("El Juego " + j.getNombre() + " no ha sido agregado.");
                }
                dispose();
        } catch (ExcepcionMia ex) {
            Logger.getLogger(IngresarJuego.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1OkActionPerformed

    private void Botonest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botonest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Botonest2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresarJuego dialog = new IngresarJuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Boton1dif;
    private javax.swing.JRadioButton Boton1inter;
    private javax.swing.JRadioButton Boton1suerte;
    private javax.swing.JRadioButton Boton2dif;
    private javax.swing.JRadioButton Boton2inter;
    private javax.swing.JRadioButton Boton2suerte;
    private javax.swing.JRadioButton Boton3dif;
    private javax.swing.JRadioButton Boton3inter;
    private javax.swing.JRadioButton Boton3suerte;
    private javax.swing.JRadioButton Boton4dif;
    private javax.swing.JRadioButton Boton4inter;
    private javax.swing.JRadioButton Boton4suerte;
    private javax.swing.JRadioButton Boton5dif;
    private javax.swing.JRadioButton Boton5inter;
    private javax.swing.JRadioButton Boton5suerte;
    private javax.swing.JRadioButton Botonest1;
    private javax.swing.JRadioButton Botonest2;
    private javax.swing.JRadioButton Botonest3;
    private javax.swing.JRadioButton Botonest4;
    private javax.swing.JRadioButton Botonest5;
    private javax.swing.ButtonGroup GrupoInteraccion;
    private javax.swing.ButtonGroup GrupoSuerte;
    private javax.swing.ButtonGroup buttonGroup1Experiencia;
    private javax.swing.ButtonGroup grupodificultad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Ok;
    private javax.swing.JComboBox<String> jComboBox1Año;
    private javax.swing.JComboBox<String> jComboBox1Duracion;
    private javax.swing.JComboBox<String> jComboBox1Expansion;
    private javax.swing.JComboBox<String> jComboBox1NJugMax;
    private javax.swing.JComboBox<String> jComboBox1NumJugMin;
    private javax.swing.JComboBox<String> jComboBox1dueño;
    private javax.swing.JComboBox<String> jComboBox1listadojuegos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1Nombre;
    private javax.swing.JTextField jTextField1disenador;
    private javax.swing.JTextField jTextField2temática;
    // End of variables declaration//GEN-END:variables
}
