/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfazGráfica;

import ControladorDAO.GestionBBDD;
import ControladorDAO.InterfazDAO;
import Excepciones.ExcepcionMia;
import Modelo.Juego;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardolucasmunozdelucas
 */
public class Modificar2 extends javax.swing.JDialog {

    StringBuilder userInput = new StringBuilder();
    private InterfazDAO daoEst = new GestionBBDD();
    ;
    private ArrayList<Juego> juegos = new ArrayList<>();
    Juego j;
    Juego z;
    String juegoSelecionado;

    int id;
    private String nombreFinal;
    String disenador;
    int año;
    int numJugMax;
    int numJugMin;
    int duracion;
    String tematica;
    int dificultad;
    int estrategia;
    int suerte;
    int interaccion;
    String dueno;
    boolean expansion;
    String expansionDe;
    String descripcion;

    /**
     * Creates new form Buscar
     */
    public Modificar2(java.awt.Frame parent, boolean modal) throws ExcepcionMia {
        super(parent, modal);
        initComponents();

        jTextField1Buscador.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char keyChar = e.getKeyChar();
                if (Character.isLetter(keyChar) || Character.isWhitespace(keyChar)) {
                    userInput.append(keyChar);
                } else if (keyChar == KeyEvent.VK_BACK_SPACE && userInput.length() > 0) {
                    userInput.deleteCharAt(userInput.length() - 1);
                }

                // Actualizar ComboBox
                actualizarComboBox();
                actualizarTextFields();
                

            }
        });

        jComboBox1listadojuegos.setEnabled(false);
        jComboBox2esExpansion.setEnabled(false);

        jComboBox2esExpansion.addItem("si");
        jComboBox2esExpansion.addItem("no");

        try {
            for (Juego s : daoEst.leerTodos()) {
                if (s.isExpansion() == false) {
                    jComboBox1listadojuegos.addItem(String.valueOf(s.getNombre()));
                }
            }
        } catch (ExcepcionMia ex) {
            Logger.getLogger(IngresarJuego.class.getName()).log(Level.SEVERE, null, ex);
        }

        jComboBox2esExpansion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jComboBox2esExpansion.getSelectedItem() != null
                        && jComboBox2esExpansion.getSelectedItem().toString().equalsIgnoreCase("si")) {
                    jComboBox1listadojuegos.setEnabled(true);
                } else {
                    jComboBox1listadojuegos.setEnabled(false);
                }
            }
        });

    }

    private void actualizarComboBox() {

        if (userInput.length() == 0) {
            jComboBox1Juegosencontrados.removeAllItems();
            jComboBox2esExpansion.setEnabled(false);
            return;
        }
        try {
//            juegos = daoEst.buscarporNombreConLetras(userInput.toString() + "%");
            juegos = daoEst.buscarporNombreConLetras(userInput.toString());
            

        } catch (ExcepcionMia ex) {
            Logger.getLogger(Modificar2.class.getName()).log(Level.SEVERE, null, ex);
        }

        jComboBox1Juegosencontrados.removeAllItems();
        if (!juegos.isEmpty()) {
            for (Juego j : juegos) {
                jComboBox1Juegosencontrados.addItem(j.getNombre());
                jComboBox2esExpansion.setEnabled(true);
                jComboBox1Juegosencontrados.showPopup();
            }
        } else {
            jComboBox1Juegosencontrados.addItem("---");
        }

        System.out.println("Texto actual: " + userInput.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1Juegosencontrados = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2okfinal = new javax.swing.JButton();
        jTextField1Nombre = new javax.swing.JTextField();
        jTextField1numJugMax = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1JugMin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1Dura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1Difi = new javax.swing.JTextField();
        jTextField2estra = new javax.swing.JTextField();
        jTextField1Suert = new javax.swing.JTextField();
        jTextField1Inter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1Buscador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1listadojuegos = new javax.swing.JComboBox<>();
        jComboBox2esExpansion = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jTextField1Disenador = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField1Año = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Temática = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField1Dueno = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1Juegosencontrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1JuegosencontradosActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jButton2okfinal.setText("Salir");
        jButton2okfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2okfinalActionPerformed(evt);
            }
        });

        jLabel2.setText("Nº jugadores max:");

        jLabel3.setText("Numero jugadores min:");

        jLabel4.setText("Duracion: ");

        jLabel5.setText("Dificultad: ");

        jLabel6.setText("Estrategia:");

        jLabel7.setText("Suerte:");

        jLabel8.setText("Interacción:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel12.setText("Lista de juegos encontrados:");

        jLabel13.setText("JUEGO SELECIONADO:");

        jLabel14.setText("Descripción:");

        jLabel15.setText("¿Es expansión de un juego?:");

        jLabel9.setText("Escribe el nombre del juego:");

        jLabel10.setFont(new java.awt.Font("Hiragino Sans", 1, 18)); // NOI18N
        jLabel10.setText("MODIFICA LOS CAMPOS QUE CONSIDERE NECESARIOS:");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Los 4 siguientes parámetros rellenalos con numeros del 1 al 5 (menor nivel 1 - mayor nivel 5):");

        jLabel16.setText("Diseñador");

        jLabel18.setText("Año de creación:");

        jLabel19.setText("Temática:");

        jLabel20.setText("Dueño:");

        jLabel21.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1Dueno, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1Difi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2estra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1Suert, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1Inter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(387, 387, 387)
                                    .addComponent(jButton2okfinal)
                                    .addGap(37, 37, 37)
                                    .addComponent(jButton1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField1Disenador, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Temática, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1Año, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1numJugMax, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1JugMin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1Dura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(222, 222, 222)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2esExpansion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1listadojuegos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1Juegosencontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(82, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1Juegosencontrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox1listadojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2esExpansion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1Disenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField1Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Temática, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1numJugMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1JugMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1Dura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1Difi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2estra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1Suert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1Inter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField1Dueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2okfinal)
                    .addComponent(jButton1))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2okfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2okfinalActionPerformed

        dispose();

    }//GEN-LAST:event_jButton2okfinalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//        for (Juego k : juegos){
//            if(k.equals(new Juego(jTextField1Nombre.getText()))){
//                System.out.println("id del juego : "+ k.getId());
//            }
        id = Integer.parseInt(jLabel22.getText());
        nombreFinal = jTextField1Nombre.getText();
        disenador = jTextField1Disenador.getText();

        tematica = Temática.getText();
        dueno = jTextField1Dueno.getText();
        expansionDe = jComboBox1listadojuegos.getSelectedItem().toString();
        descripcion = jTextArea1.getText();

        if (nombreFinal.isEmpty() || disenador.isEmpty() || tematica.isEmpty() || dueno.isEmpty() || expansionDe.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se puede dejar campos en blanco", "Datos vacíos", JOptionPane.WARNING_MESSAGE);

        } else {
            boolean ok = true;
            Calendar cal = Calendar.getInstance();
            try {
                do {
                    año = Integer.parseInt(jTextField1Año.getText());
                    numJugMax = Integer.parseInt(jTextField1numJugMax.getText());
                    numJugMin = Integer.parseInt(jTextField1JugMin.getText());
                    duracion = Integer.parseInt(jTextField1Dura.getText());
                    dificultad = Integer.parseInt(jTextField1Difi.getText());
                    estrategia = Integer.parseInt(jTextField2estra.getText());
                    suerte = Integer.parseInt(jTextField1Suert.getText());
                    interaccion = Integer.parseInt(jTextField1Inter.getText());
                    try {
                        if (año > cal.get(Calendar.YEAR) + 1 || año < 1980 || numJugMax < numJugMin) {
                            JOptionPane.showMessageDialog(this, "La año debe estar entre 1980 ", "Error ", JOptionPane.WARNING_MESSAGE);
                            return;
                        } else {
                            ok = false;
                        }

                        if (duracion < 5 || duracion > 250) {
                            JOptionPane.showMessageDialog(this, "El numero debe ser entre 5 y 250 ", "Error ", JOptionPane.WARNING_MESSAGE);
                            return;
                        } else {
                            ok = false;
                        }
                        if (dificultad > 5 || dificultad < 0) {
                            JOptionPane.showMessageDialog(this, "El numero debe ser entre 0 y 5 ", "Error ", JOptionPane.WARNING_MESSAGE);
                            return;
                        } else {
                            ok = false;
                        }
                        if (estrategia > 5 || estrategia < 0) {
                            JOptionPane.showMessageDialog(this, "El numero debe ser entre 0 y 5 ", "Error ", JOptionPane.WARNING_MESSAGE);
                            return;
                        } else {
                            ok = false;
                        }
                        if (suerte > 5 || suerte < 0) {
                            JOptionPane.showMessageDialog(this, "El numero debe ser entre 0 y 5 ", "Error ", JOptionPane.WARNING_MESSAGE);
                            return;
                        } else {
                            ok = false;
                        }
                        if (interaccion > 5 || interaccion < 0) {
                            JOptionPane.showMessageDialog(this, "El numero debe ser entre 0 y 5 ", "Error ", JOptionPane.WARNING_MESSAGE);
                            return;
                        } else {
                            ok = false;
                        }
                        
                        if(jComboBox2esExpansion.getSelectedItem().toString() == "si"){
                            expansion = true;
                        }else{
                            expansion = false;
                        }

                        Juego a = new Juego(id);

                        a.setNombre(nombreFinal);
                        a.setDisenador(disenador);
                        a.setAño(año);
                        a.setDueno(dueno);
                        a.setDuracion(duracion);
                        a.setNumJugMax(numJugMax);
                        a.setNumJugMin(numJugMin);
                        a.setDificultad(dificultad);
                        a.setEstrategia(estrategia);
                        a.setSuerte(suerte);
                        a.setInteraccion(interaccion);
                        a.setExpansion(expansion);
                        a.setExpansionDe(expansionDe);
                        a.setDescripcion(descripcion);
                        a.setTematica(tematica);

                        try {

                            int juegoActualizado = daoEst.actualizarTodo(a);
                            if (juegoActualizado == 1) {
                                JOptionPane.showMessageDialog(this, "Juego actualizado", "Juego actualizado", JOptionPane.INFORMATION_MESSAGE);
                                System.out.println("El juego " + a.getNombre() + " ha sido actualizado.");
                            } else {
                                System.out.println("El juego " + a.getNombre() + " no ha sido actualizado.");
                            }
                            dispose();
                        } catch (Exception e) {
                            System.out.println("ERROR!!!  El juego " + a.getNombre() + " no ha sido actualizado.");
                        }

                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Los campos numericos deben de ser un número", "Error de tipo de dato.", JOptionPane.WARNING_MESSAGE);
                        return;     //Voy al final
                    }

                } while (ok == true);

            } catch (Exception e) {

            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1JuegosencontradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1JuegosencontradosActionPerformed
        actualizarTextFields();
    }//GEN-LAST:event_jComboBox1JuegosencontradosActionPerformed

    // Método para actualizar los TextFields basados en el juego seleccionado
    private void actualizarTextFields() {
        if (jComboBox1Juegosencontrados.getSelectedItem() != null) {
            juegoSelecionado = jComboBox1Juegosencontrados.getSelectedItem().toString();
            // Buscar el juego seleccionado en la lista de juegos
            for (Juego juego : juegos) {
                if (juego.getNombre().equals(juegoSelecionado)) {
                    j = juego;
                    break;
                }
            }
            if (j != null) {
                jLabel22.setText(String.valueOf(j.getId()));
                jTextField1Nombre.setText(j.getNombre());
                jTextField1Disenador.setText(j.getDisenador());
                jTextField1Año.setText(String.valueOf(j.getAño()));
                Temática.setText(j.getTematica());
                jTextField1numJugMax.setText(String.valueOf(j.getNumJugMax()));
                jTextField1JugMin.setText(String.valueOf(j.getNumJugMin()));
                jTextField1Dura.setText(String.valueOf(j.getDuracion()));    //Por si da problemas el casateo
                jTextField1Difi.setText(String.valueOf(j.getDificultad()));
                jTextField2estra.setText(String.valueOf(j.getEstrategia()));
                jTextField1Suert.setText(String.valueOf(j.getSuerte()));
                jTextField1Inter.setText(String.valueOf(j.getInteraccion()));
                jTextArea1.setText(j.getDescripcion());
                jTextField1Dueno.setText(j.getDueño());

                if (j.isExpansion() == true) {
                    jComboBox2esExpansion.setSelectedItem("si");
                    jComboBox1listadojuegos.setEnabled(true);
                    jComboBox1listadojuegos.setSelectedItem(j.getExpansionDe());
                } else {
                    jComboBox2esExpansion.setSelectedItem("no");
                    jComboBox1listadojuegos.setEnabled(false);
                }

            }
        }else{
            jTextField1Nombre.setText("");
             jTextField1numJugMax.setText("");
                jTextField1JugMin.setText("");
                jTextField1Dura.setText("");
                jTextField1Difi.setText("");
                jTextField2estra.setText("");
                jTextField1Suert.setText("");
                jTextField1Inter.setText("");
                jTextArea1.setText("");
                jLabel18.setText("");
                jTextField1Dueno.setText("");
                jComboBox2esExpansion.setEnabled(false);
                jComboBox1listadojuegos.setEnabled(false);
                
                jLabel22.setText("");
                jTextField1Disenador.setText("");
                jTextField1Año.setText("");
                Temática.setText("");
                
        }
    }

    private void busquedaSinResultados() {

        System.out.println("Salió lo que quería");
        JOptionPane.showMessageDialog(this, "Ningún juego encontrado con estas características", "Atención", JOptionPane.INFORMATION_MESSAGE);

    }

    private void actualizarComboBox(ArrayList<Juego> juegos) {
        jComboBox1Juegosencontrados.removeAllItems();
        for (Juego juego : juegos) {
            jComboBox1Juegosencontrados.addItem(juego.getNombre());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ExcepcionMia {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modificar2 dialog = null;
                try {
                    dialog = new Modificar2(new javax.swing.JFrame(), true);
                } catch (ExcepcionMia ex) {
                    Logger.getLogger(Modificar2.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Temática;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2okfinal;
    private javax.swing.JComboBox<String> jComboBox1Juegosencontrados;
    private javax.swing.JComboBox<String> jComboBox1listadojuegos;
    private javax.swing.JComboBox<String> jComboBox2esExpansion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1Año;
    private javax.swing.JTextField jTextField1Buscador;
    private javax.swing.JTextField jTextField1Difi;
    private javax.swing.JTextField jTextField1Disenador;
    private javax.swing.JTextField jTextField1Dueno;
    private javax.swing.JTextField jTextField1Dura;
    private javax.swing.JTextField jTextField1Inter;
    private javax.swing.JTextField jTextField1JugMin;
    private javax.swing.JTextField jTextField1Nombre;
    private javax.swing.JTextField jTextField1Suert;
    private javax.swing.JTextField jTextField1numJugMax;
    private javax.swing.JTextField jTextField2estra;
    // End of variables declaration//GEN-END:variables
}
